parameters:
    common.entity.blog.class: Ace\CommonBundle\Entity\Blog
    common.entity.event.class: Ace\CommonBundle\Entity\Event

services:
    common.repository.blog:
        class: Ace\CommonBundle\Entity\Repository\BlogRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - %common.entity.blog.class%

    common.repository.event:
        class: Ace\CommonBundle\Entity\Repository\EventRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - %common.entity.event.class%