vich_uploader:
    db_driver: orm
    mappings:
        blog_image:
            uri_prefix:         /upload/blog/images
            upload_destination: %kernel.root_dir%/../web/upload/blog/images

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

            namer:              vich_uploader.namer_origname